<template>
    <input type="text" class="form-control m-input" :name="inputname" :value="result" placeholder="Autogenerated">
</template>

<script type="text/babel">
    import getSlug from 'speakingurl';

    export default {
        name: 'Translit',
        props: {
            inputname: {
                default: 'slug'
            },
            idelem: {
                default: '#translit-it'
            },
            oldval: {
                default: ''
            },
        },
        data() {
            return {
                result: ''
            }
        },
        created() {
            this.result = this.oldval;
        },
        mounted() {
            let elem = $(this.idelem);
            elem.keyup(() => {
                elem.focus();
                this.result = getSlug(elem.val(),{
                    separator: '-',
                    custom: {
                        'ə': 'e',
                        'ü': 'u',
                        'ç': 'ch',
                        'ğ': 'g',
                        'ö': 'o',
                        'ş': 'sh'
                    },
                });
            })
        }
    }
</script>